Repository Palgona/Backend, pull requests merged in 2024-02, with the labels that each got.

#11 Feat/#2 유저 관련 API 구현
  src/main/java/com/palgona/palgona/common/dto/CustomMemberDetails.java
  src/main/java/com/palgona/palgona/controller/MemberController.java
  src/main/java/com/palgona/palgona/dto/MemberDetailResponse.java
  src/main/java/com/palgona/palgona/dto/MemberResponse.java
  src/main/java/com/palgona/palgona/dto/MemberUpdateRequest.java
  src/main/java/com/palgona/palgona/dto/MemberUpdateRequestWithoutImage.java
  src/main/java/com/palgona/palgona/repository/MemberRepository.java
  src/main/java/com/palgona/palgona/service/MemberService.java
Labels: 기능 구현

#12 fix: 상대방 정보 조회할 때 마일리지 조회되는 문제 해결 (#7)
  src/main/java/com/palgona/palgona/controller/MemberController.java
  src/main/java/com/palgona/palgona/service/MemberService.java
Labels: bug

#15 Feat/#14 이미지 삭제 기능 추가
  src/main/java/com/palgona/palgona/service/MemberService.java
  src/main/java/com/palgona/palgona/service/image/S3Service.java
Labels: 기능 구현

#13 Feat/#9 상품 crud 기본 뼈대 로직
  src/main/java/com/palgona/palgona/controller/ProductController.java
  src/main/java/com/palgona/palgona/domain/image/Image.java
  src/main/java/com/palgona/palgona/domain/product/Category.java
  src/main/java/com/palgona/palgona/domain/product/Product.java
  src/main/java/com/palgona/palgona/domain/product/ProductImage.java
  src/main/java/com/palgona/palgona/dto/ProductCreateRequest.java
  src/main/java/com/palgona/palgona/dto/ProductResponse.java
  src/main/java/com/palgona/palgona/repository/ImageRepository.java
  src/main/java/com/palgona/palgona/repository/ProductImageRepository.java
  src/main/java/com/palgona/palgona/repository/ProductRepository.java
  src/main/java/com/palgona/palgona/service/ProductService.java
Labels: 기능 구현

#16 Feat/#3 입찰 등록 및 입찰 목록 구현
  src/main/java/com/palgona/palgona/controller/BiddingController.java
  src/main/java/com/palgona/palgona/domain/bidding/Bidding.java
  src/main/java/com/palgona/palgona/domain/bidding/BiddingStatus.java
  src/main/java/com/palgona/palgona/domain/product/Product.java
  src/main/java/com/palgona/palgona/dto/BiddingAttemptRequest.java
  src/main/java/com/palgona/palgona/dto/BiddingPageResponse.java
  src/main/java/com/palgona/palgona/repository/BiddingRepository.java
  src/main/java/com/palgona/palgona/service/BiddingService.java
Labels: 기능 구현

#19 Feat/#3 입찰 마감 API 구현
  src/main/java/com/palgona/palgona/PalgonaApplication.java
  src/main/java/com/palgona/palgona/domain/bidding/Bidding.java
  src/main/java/com/palgona/palgona/domain/bidding/BiddingState.java
  src/main/java/com/palgona/palgona/domain/member/Member.java
  src/main/java/com/palgona/palgona/repository/BiddingRepository.java
  src/main/java/com/palgona/palgona/service/BatchScheduler.java
  src/main/java/com/palgona/palgona/service/BiddingService.java
  src/main/resources/example.sql
Labels: 기능 구현

#18 feat: ExceptionHandler 설정 (#17)
  src/main/java/com/palgona/palgona/common/error/advice/GlobalExceptionHandler.java
  src/main/java/com/palgona/palgona/common/error/code/ErrorCode.java
  src/main/java/com/palgona/palgona/common/error/code/MemberErrorCode.java
  src/main/java/com/palgona/palgona/common/error/dto/response/ErrorResponse.java
  src/main/java/com/palgona/palgona/common/error/exception/BusinessException.java
  src/main/java/com/palgona/palgona/service/MemberService.java
Labels: 기능 구현

#21 Feat/#9 상품 삭제 및 수정 작업 로직 추가
  src/main/java/com/palgona/palgona/controller/ProductController.java
  src/main/java/com/palgona/palgona/domain/image/Image.java
  src/main/java/com/palgona/palgona/domain/product/Product.java
  src/main/java/com/palgona/palgona/domain/product/ProductImage.java
  src/main/java/com/palgona/palgona/domain/product/ProductState.java
  src/main/java/com/palgona/palgona/dto/ProductUpdateRequest.java
  src/main/java/com/palgona/palgona/repository/BiddingRepository.java
  src/main/java/com/palgona/palgona/repository/ProductImageRepository.java
  src/main/java/com/palgona/palgona/service/ProductService.java
Labels: 기능 구현

#26 feat: 상품 추가, 수정, 삭제 트랜잭션 처리 추가 (#9)
  src/main/java/com/palgona/palgona/service/ProductService.java
Labels: 기능 구현

#33 Feat/#24 Bidding에 예외사항들 추가
  src/main/java/com/palgona/palgona/common/error/code/BiddingErrorCode.java
  src/main/java/com/palgona/palgona/controller/BiddingController.java
  src/main/java/com/palgona/palgona/repository/BiddingRepository.java
  src/main/java/com/palgona/palgona/service/BiddingService.java
  src/test/java/com/palgona/palgona/service/bidding/BiddingServiecTest.java
Labels: 기능 구현

#32 Feat/#31 맴버 조회 API 페이징 처리
  build.gradle
  src/main/java/com/palgona/palgona/common/dto/response/SliceResponse.java
  src/main/java/com/palgona/palgona/common/error/code/MemberErrorCode.java
  src/main/java/com/palgona/palgona/common/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/palgona/palgona/config/QuerydslConfig.java
  src/main/java/com/palgona/palgona/config/SecurityConfig.java
  src/main/java/com/palgona/palgona/controller/MemberController.java
  src/main/java/com/palgona/palgona/repository/member/MemberRepository.java
  src/main/java/com/palgona/palgona/repository/member/MemberRepositoryCustom.java
  src/main/java/com/palgona/palgona/repository/member/MemberRepositoryImpl.java
  src/main/java/com/palgona/palgona/service/LoginService.java
  src/main/java/com/palgona/palgona/service/MemberService.java
Labels: 기능 구현

#34 Feat/#29 인증 필터 방식 변경
  src/main/java/com/palgona/palgona/common/error/advice/GlobalExceptionHandler.java
  src/main/java/com/palgona/palgona/common/error/code/AuthErrorCode.java
  src/main/java/com/palgona/palgona/common/error/code/MemberErrorCode.java
  src/main/java/com/palgona/palgona/common/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/palgona/palgona/common/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/palgona/palgona/common/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/palgona/palgona/common/jwt/util/JwtUtils.java
  src/main/java/com/palgona/palgona/common/jwt/util/TokenExtractor.java
  src/main/java/com/palgona/palgona/config/SecurityConfig.java
  src/main/java/com/palgona/palgona/controller/MemberController.java
  src/main/java/com/palgona/palgona/domain/member/Member.java
  src/main/java/com/palgona/palgona/service/LoginService.java
  src/main/java/com/palgona/palgona/service/MemberService.java
Labels: bug, 기능 구현

#27 Feat/#22 상품 찜 추가 및 삭제 로직 추가
  src/main/java/com/palgona/palgona/common/error/code/BookmarkErrorCode.java
  src/main/java/com/palgona/palgona/controller/BookmarkController.java
  src/main/java/com/palgona/palgona/domain/bookmark/Bookmark.java
  src/main/java/com/palgona/palgona/repository/BookmarkRepository.java
  src/main/java/com/palgona/palgona/service/BookmarkService.java
Labels: 기능 구현

#37 fix: 상품 예외 처리 방식 수정 (#9)
  src/main/java/com/palgona/palgona/common/error/code/ProductErrorCode.java
  src/main/java/com/palgona/palgona/service/ProductService.java
Labels: bug
