Repository Palgona/Backend, pull requests merged in 2024-03, with the labels that each got.

#41 Feat/#36 로그아웃 기능
  src/main/java/com/palgona/palgona/common/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/palgona/palgona/common/jwt/util/JwtService.java
  src/main/java/com/palgona/palgona/common/jwt/util/JwtUtils.java
  src/main/java/com/palgona/palgona/common/redis/RedisUtils.java
  src/main/java/com/palgona/palgona/config/RedisConfig.java
  src/main/java/com/palgona/palgona/config/SecurityConfig.java
  src/main/java/com/palgona/palgona/controller/LoginController.java
  src/main/java/com/palgona/palgona/domain/RefreshToken.java
  src/main/java/com/palgona/palgona/dto/AuthToken.java
  src/main/java/com/palgona/palgona/repository/RefreshTokenRepository.java
  src/main/java/com/palgona/palgona/service/LoginService.java
  src/test/java/com/palgona/palgona/PalgonaApplicationTests.java
  src/test/java/com/palgona/palgona/controller/login/LoginControllerTest.java
  src/test/java/com/palgona/palgona/controller/member/MemberControllerTest.java
  src/test/java/com/palgona/palgona/controller/member/MemberInitializer.java
  src/test/java/com/palgona/palgona/service/login/LoginServiceTest.java
  src/test/java/com/palgona/palgona/service/member/MemberServiceTest.java
Labels: 기능 구현, 테스트

#38 Feat/#23 마일리지 조회 및 충전 로직 추가
  src/main/java/com/palgona/palgona/common/error/code/MileageErrorCode.java
  src/main/java/com/palgona/palgona/controller/MileageHistoryController.java
  src/main/java/com/palgona/palgona/domain/mailage/MileageHistory.java
  src/main/java/com/palgona/palgona/domain/mailage/MileageState.java
  src/main/java/com/palgona/palgona/domain/member/Member.java
  src/main/java/com/palgona/palgona/dto/MileageChargeRequest.java
  src/main/java/com/palgona/palgona/repository/MileageHistoryRepository.java
  src/main/java/com/palgona/palgona/service/MileageHistoryService.java
Labels: 기능 구현

#42 docs: 상품 api 설명 추가 (#9)
  src/main/java/com/palgona/palgona/controller/ProductController.java
Labels: documentation

#44 docs: 마일리지 api 설명 추가 (#23)
  src/main/java/com/palgona/palgona/controller/MileageHistoryController.java
Labels: documentation

#46 Feat/#45 상품 관련 API 수정
  src/main/java/com/palgona/palgona/common/error/code/ProductErrorCode.java
  src/main/java/com/palgona/palgona/controller/ProductController.java
  src/main/java/com/palgona/palgona/domain/product/Product.java
  src/main/java/com/palgona/palgona/dto/ProductDetailResponse.java
  src/main/java/com/palgona/palgona/dto/ProductResponse.java
  src/main/java/com/palgona/palgona/repository/BookmarkRepository.java
  src/main/java/com/palgona/palgona/repository/ImageRepository.java
  src/main/java/com/palgona/palgona/repository/ProductImageRepository.java
  src/main/java/com/palgona/palgona/repository/product/ProductRepository.java
  src/main/java/com/palgona/palgona/repository/product/querydto/ProductDetailQueryResponse.java
  src/main/java/com/palgona/palgona/service/ProductService.java
Labels: 수정필요

#53 Feat/#47
  src/main/java/com/palgona/palgona/domain/product/ProductState.java
  src/test/java/com/palgona/palgona/service/product/ProductServiceCreateTest.java
  src/test/java/com/palgona/palgona/service/product/ProductServiceDeleteTest.java
  src/test/java/com/palgona/palgona/service/product/ProductServiceReadTest.java
  src/test/java/com/palgona/palgona/service/product/ProductServiceUpdateTest.java
Labels: 테스트

#58 Feat/#6 Dev 환경 CICD 구축
  .github/workflows/dev.yml
  Dockerfile
  build.gradle
Labels: 환경설정, 기능 구현

#60 fix: refrshToken 삭제하고 flush() 호출되게 수정
  src/main/java/com/palgona/palgona/common/jwt/util/JwtService.java
Labels: 수정필요
